version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: goapp
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongo-data:
