basePath: /
host: localhost:8000
info:
  contact: {}
  description: This is a sample server for golang-Curd-Oprations-With-Mongodb.
  title: golang-Curd-Oprations-With-Mongodb
  version: "1.0"
paths: {}
swagger: "2.0"
