name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Install Golang Dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Deploy to Development
      run: echo "Deploying to Development environment"

  deploy_stage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/stage'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Deploy to Staging
      run: echo "Deploying to Staging environment"

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Deploy to Production
      run: echo "Deploying to Production environment"
